name: Deploy to Azure VM

on:
 workflow_call:
  inputs:
    debug:
       description: "Enable verbose logging"
       required: false
       default: false
       type: boolean
    image-name:
      required: true
      type: string
    image-tag:
       required: true
       type: string
    container-name:
       required: true
       type: string
    app-port:
       required: true
       type: number
  secrets:
      VM_HOST:
       required: true
      VM_USER:
       required: true 
      VM_SSH_KEY:
       required: true
      DOCKERHUB_USERNAME:
       required: true
      DOCKERHUB_TOKEN:
       required: true
        
jobs:
 deploy:
   name: deploy to Azure VM
   runs-on: ubuntu-latest
   env:
      DEBUG: ${{inputs.debug}}

   steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
                  DEBUG="${{ inputs.debug }}"
                  # Conditional verbose mode
                  if [[ "$DEBUG" == "true" ]]; then
                    echo "🔍 Debug mode enabled"
                    set -x
                  else
                    echo "▶ Running in normal mode"
                  fi
        
                  echo "=== Versioning info ==="

                  IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"

                  docker pull "$IMAGE"
      
                  docker stop ${{ inputs.container-name }} || true
                  docker rm ${{ inputs.container-name }} || true
      
                  docker run -d --name ${{ inputs.container-name }} -p 80:${{ inputs.app-port }} "$IMAGE"
