name: tag and push image

on:
  workflow_call:
    inputs:
      debug:
       description: "Enable verbose logging"
       required: false
       default: false
       type: boolean
      image-name:
        required: true
        type: string
      build-context:
        required: true
        default: .
        type: string
      dockerfile-path:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
       required: true
      DOCKERHUB_USERNAME:
       required: true

permissions:
 contents: write      
      
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{inputs.debug}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch git tags
        run: git fetch --tags
        
      - name: Decide version bump
        id: version
        # env: 
        #   DEBUG: ${{inputs.debug}}
        run: |
          # Conditional verbose mode
          if [[ "$DEBUG" == "true" ]]; then
            echo "🔍 Debug mode enabled"
            set -x
          else
            echo "▶ Running in normal mode"
          fi

          echo "=== Versioning info ==="
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          SOURCE_BRANCH="${GITHUB_HEAD_REF}"
          TARGET_BRANCH="${GITHUB_BASE_REF}"

          echo "Source branch: $SOURCE_BRANCH"
          echo "Target branch: $TARGET_BRANCH"

          SHOULD_TAG=false

          if [[ "$SOURCE_BRANCH" == "hotfix" && "$TARGET_BRANCH" == "release" ]]; then
            PATCH=$((PATCH + 1))
            SHOULD_TAG=true
          elif [[ "$SOURCE_BRANCH" == "main" && "$TARGET_BRANCH" == "release" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            SHOULD_TAG=true
          fi

          if [[ "$SHOULD_TAG" == "true" ]]; then
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "NEW_TAG=v$NEW_VERSION" >> $GITHUB_ENV
            echo "LATEST_TAG=$NEW_VERSION" >> $GITHUB_ENV
          fi

      - name: Push Git tag
        if: env.NEW_TAG != ''
        run: |
          # Conditional verbose mode
          if [[ "$DEBUG" == "true" ]]; then
            echo "🔍 Debug mode enabled"
            set -x
          else
            echo "▶ Running in normal mode"
          fi

          echo "=== Versioning info ==="
          # TAG="${{ steps.version.outputs.new_tag }}"

          # if git rev-parse "$TAG" >/dev/null 2>&1; then
          #   echo "Tag already exists. Skipping."
          #   exit 0
          # fi

          git config user.name "riti-bhandari"
          git config user.email "ritibhandari16@gmail.com"
          git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        if: env.NEW_TAG != ''
        run: |
          docker build -t ${ inputs.DOCKERHUB_USERNAME }/${{ inputs.image-name }}:$LATEST_TAG -f ${{ inputs.dockerfile-path }} ${{ inputs.build-context }}
            
          docker push ${ inputs.DOCKERHUB_USERNAME }/${{ inputs.image-name }}:$LATEST_TAG


          
