name: Update Deployment Repo Image Tag

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      deployment-repo:
        required: true
        type: string
      # values-file:
      #   required: true
      #   type: string
    secrets:
      GH_PAT:
        required: true

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.deployment-repo }}
          token: ${{ secrets.GH_PAT }}
          path: deployment-repo

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

# 3️⃣ Update Image Tag in Correct Environment File
      - name: Update image tag
        run: |
          cd deployment-repo
          
          VALUES_FILE="environments/${{ inputs.environment }}/values.yaml"
          CHART_FILE="helm-chart/Chart.yaml"
          
          
          echo "Updating file: $VALUES_FILE"
          echo "Updating file: $CHART_FILE"
          
          yq e ".image.tag = \"${{ inputs.image-tag }}\"" -i $VALUES_FILE
          yq e ".appVersion = "\${{ inputs.image-tag }}\"" -i $CHART_FILE

      # 4️⃣ Commit Changes
      - name: Commit changes
        run: |
          cd deployment-repo
          git config user.name "riti-bhandari"
          git config user.email "riti-bhandari16@gmail.com"
          
          git add .
          git commit -m "Update image tag to ${{ inputs.image-tag }} for ${{ inputs.environment }}" || echo "No changes to commit"

      # 5️⃣ Push Changes
      - name: Push changes
        run: |
          cd deployment-repo
          git push



          
      # - name: Update image tag using yq
      #   run: |
      #     cd deployment-repo
      #     yq e '.image.tag = "${{ inputs.image-tag }}"' -i ${{ inputs.values-file }}

      # - name: Commit and Push changes
      #   run: |
      #     cd deployment-repo
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      #     git add ${{ inputs.values-file }}
      #     git commit -m "Update image tag to ${{ inputs.image-tag }}"
      #     git push
