name: Update Deployment Repo Image Tag

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      deployment-repo:
        required: true
        type: string
      values-file:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.deployment-repo }}
          token: ${{ secrets.GH_PAT }}
          path: deployment-repo

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update image tag using yq
        run: |
          cd deployment-repo
          yq e '.image.tag = "${{ inputs.image-tag }}"' -i ${{ inputs.values-file }}

      - name: Commit and Push changes
        run: |
          cd deployment-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ inputs.values-file }}
          git commit -m "Update image tag to ${{ inputs.image-tag }}"
          git push
