name: Update Deployment Repo Image Tag

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      deployment-repo:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

permissions:
  contents: write

jobs:
  update-and-package:
    runs-on: ubuntu-latest
    steps:
      # 1 Checkout Deployment Repo
      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.deployment-repo }}
          token: ${{ secrets.GH_PAT }}
          path: deployment-repo

        # 2 Install yq
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

        # 3️ Setup Helm
      - name: Setup Helm
        uses: azure/setup-helm@v4

      # 4️ Update Image Tag + App Version
      - name: Update image tag and appVersion
        run: |
          cd deployment-repo
          
          VALUES_FILE="apps/app1/app1.yaml"
          CHART_FILE="apps/helm-chart/Chart.yaml"
          
          echo "Updating image tag in: $VALUES_FILE"
          yq e ".image.tag = \"${{ inputs.image-tag }}\"" -i $VALUES_FILE
          
          echo "Updating appVersion in: $CHART_FILE"
          yq e ".appVersion = \"${{ inputs.image-tag }}\"" -i $CHART_FILE
