name: Update Deployment Repo Image Tag

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      deployment-repo:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

permissions:
  contents: write

jobs:
  update-and-package:
    runs-on: ubuntu-latest
